
import { Artwork } from './types';

export const ARTWORKS_DATA: Artwork[] = [
  {
    id: 1,
    title: "Serenity in Stone",
    artist: "Elena Petrova",
    year: 2023,
    imageSrc: "https://images.unsplash.com/photo-1588675646184-f5b0b0b0b2de?q=80&w=1887&auto=format&fit=crop",
    description: "Sebuah studi tentang ketenangan, di mana tekstur batu yang kasar bertemu dengan kelembutan cahaya pagi. Karya ini menangkap momen keheningan abadi yang ditemukan di alam.",
    medium: "Fotografi Digital",
    dimensions: "100cm x 150cm",
    position: { pitch: 0, yaw: -150 },
  },
  {
    id: 2,
    title: "Whispers of the Forest",
    artist: "Liam O'Connell",
    year: 2024,
    imageSrc: "https://images.unsplash.com/photo-1448375240586-882707db888b?q=80&w=2070&auto=format&fit=crop",
    description: "Permainan cahaya dan bayangan di antara pepohonan kuno, menciptakan permadani visual yang berbicara tentang pertumbuhan, ketahanan, dan keajaiban tersembunyi di alam liar.",
    medium: "Lukisan Akrilik di atas Kanvas",
    dimensions: "120cm x 90cm",
    position: { pitch: 5, yaw: -90 },
  },
  {
    id: 3,
    title: "Golden Hour Abstract",
    artist: "Aya Tanaka",
    year: 2022,
    imageSrc: "https://images.unsplash.com/photo-1558591710-4b4a1ae0f04d?q=80&w=1887&auto=format&fit=crop",
    description: "Representasi abstrak dari kehangatan dan cahaya yang memudar di penghujung hari. Sapuan kuas yang energik dan warna-warna keemasan membangkitkan perasaan nostalgia dan harapan.",
    medium: "Cat Minyak di atas Linen",
    dimensions: "80cm x 100cm",
    position: { pitch: -2, yaw: -30 },
  },
  {
    id: 4,
    title: "Coastal Drift",
    artist: "Marcus Reid",
    year: 2023,
    imageSrc: "https://images.unsplash.com/photo-1516698303491-862d2a4a3a63?q=80&w=1887&auto=format&fit=crop",
    description: "Karya ini mengeksplorasi ritme laut, dengan bentuk organik dan palet warna yang diredam yang terinspirasi oleh kayu apung, pasir basah, dan cakrawala yang berkabut.",
    medium: "Media Campuran di atas Panel Kayu",
    dimensions: "150cm x 75cm",
    position: { pitch: 2, yaw: 30 },
  },
    {
    id: 5,
    title: "Urban Geometry",
    artist: "Sofia Chen",
    year: 2024,
    imageSrc: "https://images.unsplash.com/photo-1618172193622-ae2d025f4032?q=80&w=1964&auto=format&fit=crop",
    description: "Sebuah komposisi minimalis yang menemukan keindahan dalam garis-garis bersih dan bentuk-bentuk arsitektur modern. Ini adalah meditasi tentang keteraturan dan ruang dalam lanskap perkotaan.",
    medium: "Cetakan Seni Rupa Giclée",
    dimensions: "70cm x 70cm",
    position: { pitch: -5, yaw: 90 },
  },
  {
    id: 6,
    title: "Ethereal Bloom",
    artist: "Isabella Rossi",
    year: 2022,
    imageSrc: "https://images.unsplash.com/photo-1567539884609-f5914a38e8a6?q=80&w=1887&auto=format&fit=crop",
    description: "Penangkapan bunga yang fana dalam keadaan mekar penuh, menggunakan fokus lembut dan pencahayaan halus untuk menciptakan kualitas seperti mimpi, hampir halus.",
    medium: "Seni Kaca Patung",
    dimensions: "Diameter 40cm",
    position: { pitch: 8, yaw: 135 },
  },
];